import { Room, Booking } from './types';

export const STANDARD_TIME_SLOTS = [
  '07:30 - 09:30',
  '09:45 - 11:45',
  '13:00 - 15:00',
  '15:15 - 17:15',
  '17:30 - 19:30',
  '19:45 - 21:45',
];

export const BUILDINGS_LIST = [
  'Tất cả',
  'Tòa nhà A3',
  'Tòa nhà A1',
  'Tòa nhà A2',
  'Thư viện Trung tâm',
  'Tòa nhà V',
  'Khu Thực nghiệm K',
];

export const MOCK_ROOMS: Room[] = [
  {
    id: 'r-101',
    name: 'Lab A3-101 (Software Eng)',
    building: 'Tòa nhà A3',
    capacity: 35,
    room_type: 'computer_lab',
    amenities: ['40 PC Core i7', 'Điều hòa đôi', 'Máy chiếu Sony 4K', 'Gigabit LAN', 'Bảng kính'],
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    description: 'Phòng thực hành Công nghệ Phần mềm & Lập trình Di động',
    is_active: 1,
  },
  {
    id: 'r-102',
    name: 'Lab A3-102 (AI & Data Science)',
    building: 'Tòa nhà A3',
    capacity: 30,
    room_type: 'computer_lab',
    amenities: ['30 PC RTX 4080', 'Điều hòa trung tâm', 'Bảng tương tác thông minh', 'Mạng 10Gbps'],
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    description: 'Phòng thí nghiệm Trí tuệ nhân tạo và Khoa học dữ liệu VKU',
    is_active: 1,
  },
  {
    id: 'r-103',
    name: 'Lab A3-201 (Cybersecurity)',
    building: 'Tòa nhà A3',
    capacity: 40,
    room_type: 'computer_lab',
    amenities: ['40 PC Core i9', 'Mạng cô lập Isolated LAN', 'Máy chiếu kép', 'Điều hòa'],
    image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    description: 'Phòng thực hành An toàn thông tin và Mạng máy tính',
    is_active: 1,
  },
  {
    id: 'r-104',
    name: 'Lab A3-202 (Mobile & Cloud)',
    building: 'Tòa nhà A3',
    capacity: 32,
    room_type: 'computer_lab',
    amenities: ['32 iMac 24-inch', 'Bộ phát Wi-Fi 6 Dedicated', 'Bảng kính', 'Điều hòa đôi'],
    image_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80',
    description: 'Phòng phát triển Ứng dụng Di động iOS/Android và Cloud',
    is_active: 1,
  },
  {
    id: 'r-105',
    name: 'Phòng Hội thảo A1-301',
    building: 'Tòa nhà A1',
    capacity: 80,
    room_type: 'meeting_room',
    amenities: ['Hệ thống âm thanh hội nghị', '2 Máy chiếu Laser', 'Mic không dây', 'Điều hòa âm trần'],
    image_url: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&q=80',
    description: 'Phòng hội thảo chuyên đề khoa học và báo cáo đồ án',
    is_active: 1,
  },
  {
    id: 'r-106',
    name: 'Phòng Nghiên cứu A1-302',
    building: 'Tòa nhà A1',
    capacity: 20,
    room_type: 'study_space',
    amenities: ['Bàn làm việc nhóm', 'Smart TV 75-inch', 'Bảng viết kính', 'Ổ cắm từng bàn'],
    image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    description: 'Không gian nghiên cứu cho giảng viên và nhóm nghiên cứu sinh viên',
    is_active: 1,
  },
  {
    id: 'r-107',
    name: 'Giảng đường A2-101',
    building: 'Tòa nhà A2',
    capacity: 120,
    room_type: 'theory_room',
    amenities: ['Màn hình LED P2.5 lớn', 'Âm thanh vòm', 'Bục giảng điện tử', 'Điều hòa công suất lớn'],
    image_url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
    description: 'Giảng đường bậc thang phục vụ học lý thuyết chung và sự kiện',
    is_active: 1,
  },
  {
    id: 'r-108',
    name: 'Giảng đường A2-102',
    building: 'Tòa nhà A2',
    capacity: 100,
    room_type: 'theory_room',
    amenities: ['Máy chiếu siêu nét', 'Mic trợ giảng', 'Bàn ghế liền tựa', 'Điều hòa trung tâm'],
    image_url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80',
    description: 'Giảng đường lý thuyết tiêu chuẩn cơ sở VKU',
    is_active: 1,
  },
  {
    id: 'r-109',
    name: 'Phòng Học nhóm A2-205',
    building: 'Tòa nhà A2',
    capacity: 15,
    room_type: 'study_space',
    amenities: ['Bàn tròn di động', 'Smart TV 55-inch', 'Bảng flipchart', 'Trà & Nước miễn phí'],
    image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
    description: 'Phòng thảo luận nhóm cho sinh viên làm đồ án môn học',
    is_active: 1,
  },
  {
    id: 'r-110',
    name: 'Phòng Học nhóm A2-206',
    building: 'Tòa nhà A2',
    capacity: 18,
    room_type: 'study_space',
    amenities: ['Bàn module xếp ghép', 'Màn hình chiếu', 'Bảng trắng 2 mặt', 'Wi-Fi 6'],
    image_url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80',
    description: 'Phòng làm việc nhóm và brainstorm ý tưởng khởi nghiệp',
    is_active: 1,
  },
  {
    id: 'r-111',
    name: 'VKU Library Zone A (Yên tĩnh)',
    building: 'Thư viện Trung tâm',
    capacity: 60,
    room_type: 'study_space',
    amenities: ['Bàn đọc đơn có vách ngăn', 'Đèn học cá nhân', 'Ổ cắm sạc laptop', 'Không gian tĩnh lặng'],
    image_url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80',
    description: 'Khu tự học yên tĩnh tuyệt đối tại tầng 2 thư viện',
    is_active: 1,
  },
  {
    id: 'r-112',
    name: 'VKU Library Zone B (Nhóm mở)',
    building: 'Thư viện Trung tâm',
    capacity: 50,
    room_type: 'study_space',
    amenities: ['Ghế sofa thư giãn', 'Bàn dài làm việc nhóm', 'Cây xanh thư thái', 'Cổng sạc Type-C'],
    image_url: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80',
    description: 'Khu tự học mở, cho phép trao đổi học thuật thoải mái',
    is_active: 1,
  },
  {
    id: 'r-113',
    name: 'Thư viện - Seminar Room 1',
    building: 'Thư viện Trung tâm',
    capacity: 25,
    room_type: 'meeting_room',
    amenities: ['Máy chiếu tương tác Epson', 'Webcam Poly họp trực tuyến', 'Loa mic hội nghị Jabra'],
    image_url: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&q=80',
    description: 'Phòng sinh hoạt chuyên đề, thuyết trình đồ án tốt nghiệp',
    is_active: 1,
  },
  {
    id: 'r-114',
    name: 'Thư viện - Seminar Room 2',
    building: 'Thư viện Trung tâm',
    capacity: 30,
    room_type: 'meeting_room',
    amenities: ['TV Samsung 85-inch 4K', 'Bảng mica từ tính', 'Điều hòa Inverter', 'Ghế công thái học'],
    image_url: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?w=800&q=80',
    description: 'Phòng thuyết trình và seminar học thuật chất lượng cao',
    is_active: 1,
  },
  {
    id: 'r-115',
    name: 'Media Production Studio',
    building: 'Thư viện Trung tâm',
    capacity: 12,
    room_type: 'study_space',
    amenities: ['Phông xanh Chroma key', 'Đèn chiếu sáng chuyên dụng', 'Micro Rode PodMic', 'Cách âm cao cấp'],
    image_url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80',
    description: 'Studio thu âm podcast, quay bài giảng và video thuyết trình',
    is_active: 1,
  },
  {
    id: 'r-116',
    name: 'Smart Lab V.B101 (IoT & Robotics)',
    building: 'Tòa nhà V',
    capacity: 30,
    room_type: 'computer_lab',
    amenities: ['Bộ kit Arduino & ESP32', 'Máy in 3D Bambu Lab', 'Dụng cụ đo dao động số', 'PC trạm'],
    image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    description: 'Phòng thí nghiệm Internet of Things, Vi điều khiển và Robotics',
    is_active: 1,
  },
  {
    id: 'r-117',
    name: 'Lab V.B102 (Embedded Systems)',
    building: 'Tòa nhà V',
    capacity: 28,
    room_type: 'computer_lab',
    amenities: ['Trạm hàn chống tĩnh điện', 'Board FPGA & ARM Cortex', 'Nguồn đôi DC', 'Điều hòa đôi'],
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80',
    description: 'Phòng thực hành Hệ thống nhúng và Thiết kế vi mạch',
    is_active: 1,
  },
  {
    id: 'r-118',
    name: 'Phòng Thực hành Mạng V.B201',
    building: 'Tòa nhà V',
    capacity: 40,
    room_type: 'computer_lab',
    amenities: ['Tủ Rack Cisco Switches', 'Router băng thông cao', 'Patch panel', '40 máy PC'],
    image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80',
    description: 'Phòng thực hành cấu hình thiết bị mạng Cisco và định tuyến',
    is_active: 1,
  },
  {
    id: 'r-119',
    name: 'Phòng Đồ họa & Game V.B202',
    building: 'Tòa nhà V',
    capacity: 35,
    room_type: 'computer_lab',
    amenities: ['35 PC Intel i7 + GPU RTX 4070', 'Bảng vẽ điện tử Wacom', 'Màn hình 27-inch 2K 100% sRGB'],
    image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
    description: 'Phòng thiết kế đồ họa, dựng mô hình 3D và phát triển Game',
    is_active: 1,
  },
  {
    id: 'r-120',
    name: 'Phòng Đa năng V.B301',
    building: 'Tòa nhà V',
    capacity: 70,
    room_type: 'theory_room',
    amenities: ['2 Máy chiếu Panasonic', 'Hệ thống âm thanh hội thảo', 'Điều hòa 4 hướng thổi'],
    image_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    description: 'Phòng học lý thuyết đa năng và kiểm tra học phần',
    is_active: 1,
  },
  {
    id: 'r-121',
    name: 'Phòng Đa năng V.B302',
    building: 'Tòa nhà V',
    capacity: 65,
    room_type: 'theory_room',
    amenities: ['Bảng trượt 3 lớp', 'Máy chiếu Laser độ sáng cao', 'Bàn ghế di chuyển linh hoạt'],
    image_url: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80',
    description: 'Phòng học tương tác theo mô hình học tập kết hợp (Blended Learning)',
    is_active: 1,
  },
  {
    id: 'r-122',
    name: 'Không gian Sáng tạo VKU MakerSpace',
    building: 'Khu Thực nghiệm K',
    capacity: 45,
    room_type: 'study_space',
    amenities: ['Máy cắt laser CO2', 'Bộ dụng cụ cơ khí tạo mẫu nhanh', 'Bàn làm việc gỗ thông lớn', 'Coffee corner'],
    image_url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
    description: 'Không gian sáng chế dành cho các dự án Capstone & Khởi nghiệp sinh viên',
    is_active: 1,
  },
  {
    id: 'r-123',
    name: 'Phòng Họp Ban Chủ nhiệm K101',
    building: 'Khu Thực nghiệm K',
    capacity: 16,
    room_type: 'meeting_room',
    amenities: ['Màn hình hiển thị không dây AirPlay/Miracast', 'Bàn họp gỗ sồi', 'Ghế xoay lưới da'],
    image_url: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80',
    description: 'Phòng họp điều hành và tiếp đón doanh nghiệp hợp tác',
    is_active: 1,
  },
  {
    id: 'r-124',
    name: 'Hội trường Lớn Trực tuyến K200',
    building: 'Khu Thực nghiệm K',
    capacity: 150,
    room_type: 'theory_room',
    amenities: ['Màn hình LED sân khấu 200-inch', 'Dàn âm thanh Line Array', 'Hệ thống livestream chuyên dụng'],
    image_url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
    description: 'Hội trường diễn ra các buổi workshop, ngày hội việc làm và hackathon',
    is_active: 1,
  },
];

const today = new Date().toISOString().split('T')[0];

export const INITIAL_MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b-init-1',
    room_id: 'r-101',
    user_name: 'Trần Văn Nam',
    user_student_id: '21IT001',
    booking_date: today,
    time_slot: '07:30 - 09:30',
    purpose: 'Học nhóm Mobile App React Native',
    status: 'confirmed',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    room_name: 'Lab A3-101 (Software Eng)',
    building: 'Tòa nhà A3',
    capacity: 35,
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
  },
  {
    id: 'b-init-2',
    room_id: 'r-101',
    user_name: 'Lê Thị Thu Thảo',
    user_student_id: '21IT045',
    booking_date: today,
    time_slot: '09:45 - 11:45',
    purpose: 'Ôn thi cuối kỳ Lập trình mạng',
    status: 'confirmed',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    room_name: 'Lab A3-101 (Software Eng)',
    building: 'Tòa nhà A3',
    capacity: 35,
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
  },
  {
    id: 'b-init-3',
    room_id: 'r-111',
    user_name: 'Nguyễn Hoàng Long',
    user_student_id: '22IT102',
    booking_date: today,
    time_slot: '13:00 - 15:00',
    purpose: 'Tự học IELTS và làm đồ án tốt nghiệp',
    status: 'confirmed',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    room_name: 'VKU Library Zone A (Yên tĩnh)',
    building: 'Thư viện Trung tâm',
    capacity: 60,
    image_url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80',
  },
];
